### Get all categories
GET http://localhost:3000/api/categories
X-API-Key: SECRET
Accept: application/json

### Create new category
POST http://localhost:3000/api/categories
X-API-Key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name" : "Drink"
}

### Get category by Id
GET http://localhost:3000/api/categories/2
X-API-Key: SECRET
Accept: application/json

### Update category by id
PUT http://localhost:3000/api/categories/2
X-API-Key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name" : "Fashion"
}

### Delete category by id
DELETE http://localhost:3000/api/categories/2
X-API-Key: SECRET
Accept: application/json