// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/raihanmd/dependency_injection/app"
	"github.com/raihanmd/dependency_injection/controller"
	"github.com/raihanmd/dependency_injection/middleware"
	"github.com/raihanmd/dependency_injection/repository"
	"github.com/raihanmd/dependency_injection/service"
)

// Injectors from injector.go:

func InitializedRouter() *middleware.AuthMiddleware {
	categoryRepository := repository.NewCategoryRepository()
	db := app.NewDB()
	v := _wireValue
	validate := validator.New(v...)
	categoryService := service.NewCategoryService(categoryRepository, db, validate)
	categoryController := controller.NewCategoryController(categoryService)
	authMiddleware := app.NewRouter(categoryController)
	return authMiddleware
}

var (
	_wireValue = []validator.Option{}
)

// injector.go:

var categorySet = wire.NewSet(repository.NewCategoryRepository, service.NewCategoryService, controller.NewCategoryController)
